# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "wrap": "01_coretest.ipynb"}

modules = ["core.py",
           "coretest.py"]

git_url = "https://github.com/hlafortu/nbdevtesteur/tree/master/"

def custom_doc_links(name): return None
