# AUTOGENERATED! DO NOT EDIT! File to edit: dev/01_coretest.ipynb (unless otherwise specified).

__all__ = ['wrap']

# Cell
from .core import *
from fastscript import *

# Cell
def wrap():
    "Use the say hello function `say_hello`"
    say_hello("TOTOT")