# AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "Say hello to somebody"
    print(f"Hello {to}!")
    return "Hello " + to + "!"

# Cell
class HelloSayer:
    "Say hello to `to` using [`say_hello`](#say_hello)"
    def __init__(self, to): self.to = to
    def say(self): say_hello(self.to)